### ISSUE TITLE
Error: Content not allowed in prolog 

### ISSUE THREAD

**Issue by TURROKS** [MaltegoTech/maltego-ltc#3]
This error appears as there are 2 print statements in the config.py file for the Wigle API Key.

![Screenshot from 2023-04-14 17-28-30](https://user-images.githubusercontent.com/16016384/232057057-e073c48d-ab45-4705-9cd7-f7b0329e6da2.png)

Can see the message in the output window

![Screenshot from 2023-04-14 17-22-29](https://user-images.githubusercontent.com/16016384/232057123-9f40dce1-43d4-4054-9ec8-5fa2ee8ba8a5.png)

Commenting the 2 lines in the config file fixes the issue

![Screenshot from 2023-04-14 17-30-12](https://user-images.githubusercontent.com/16016384/232057344-05f549fa-b65f-47dd-a188-7271bc67d4c7.png)

**Comment by mt-dirk** [comment]
I'm aware of this, and it's mentioned in the README. The issue we have with the config is it will be written after installation. So I can't make changes in the default config from wigle.

**Comment by TURROKS** [comment]
Thanks Dirk, just saw the section in the README
